# プライバシー設定ファイル
# AGO Group プロファイリングシステム

masking_rules:
  # メールアドレスのマスキング
  email:
    enabled: true
    pattern: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    replacement: '***@***.***'
    partial: false  # trueにすると***@domain.comの形式

  # 電話番号のマスキング
  phone:
    enabled: true
    patterns:
      - '\d{3}-\d{4}-\d{4}'          # 090-1234-5678
      - '\d{2,4}-\d{2,4}-\d{4}'      # 03-1234-5678
      - '\(\d{2,4}\)\d{2,4}-\d{4}'  # (03)1234-5678
      - '\+\d{1,3}\s?\d{1,4}\s?\d{1,4}\s?\d{4}'  # +81 90 1234 5678
    replacement: '***-****-****'

  # 名前のマスキング
  name:
    enabled: false  # デフォルトは無効
    partial: true   # trueの場合、姓のみ表示

  # 住所のマスキング
  address:
    enabled: true
    keywords:
      - '住所'
      - '〒'
      - '都道府県'
    replacement: '[住所は削除されました]'

  # クレジットカード番号のマスキング
  credit_card:
    enabled: true
    pattern: '\b\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b'
    replacement: '****-****-****-****'

  # カスタムパターン例
  # employee_id:
  #   enabled: true
  #   pattern: 'EMP\d{6}'
  #   replacement: 'EMP******'

# センシティブフィールド（これらの単語を含むタグは自動削除）
sensitive_fields:
  - password
  - secret
  - token
  - api_key
  - private_key
  - ssn
  - social_security
  - apikey
  - auth

# 暗号化設定
encryption:
  enabled: false  # 暗号化を有効にする場合はtrue
  key_path: 'config/.encryption_key'  # 暗号化キーの保存場所

# アクセス制御設定
access_control:
  enabled: true
  default_level: 'read'
  levels:
    - none   # アクセス不可
    - read   # 読み取りのみ
    - write  # 読み書き可能
    - admin  # 管理者権限

# 匿名化設定
anonymization:
  salt: 'ago_group_2024'  # ID匿名化用のソルト