# AGOグループ業務プロファイリングシステム設定

# データソース設定
data_sources:
  emails:
    path: "data/raw/emails"
    formats: ["csv", "json", "txt"]
  documents:
    path: "data/raw/documents"
    formats: ["txt", "pdf", "docx"]
  logs:
    path: "data/raw/logs"
    formats: ["csv", "json"]

# 処理設定
processing:
  batch_size: 1000
  max_workers: 4
  encoding: "utf-8"

# 分析設定
analysis:
  min_activity_count: 5
  collaboration_threshold: 3
  workflow_pattern_min_frequency: 2

# 出力設定
output:
  profiles_path: "output/profiles"
  workflows_path: "output/workflows"
  departments_path: "output/departments"
  markdown_template_path: "templates/"

# セキュリティ設定
security:
  enable_masking: true
  mask_patterns:
    - email: "***@***.***"
    - phone: "***-****-****"
    - name: "[REDACTED]"
  
# ロギング設定
logging:
  level: "INFO"
  file: "logs/profiling.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"